name: peptidome
channels:
    - conda-forge
    - bioconda
dependencies:
    - pip
    - numpy==1.16.4
    - scipy==1.2.1
    - pandas==1.1
    - matplotlib==3.0.3
    - seaborn==0.9.0
    - biopython==1.72
    - numba
    - mpmath==1.1.0
    - scikit-learn==0.20.0
    - statsmodels==0.12.0
    - jupyter
    - Levenshtein
    - joblib
    - bioconda::snakemake
    - pip:
        - palettable
        - pyrepseq
